version: "3.8"
services:
  #  mysql_container:
  #    image: mysql:8
  #    environment:
  #      - MYSQL_ROOT_PASSWORD=secret
  #    volumes:
  #      - pericia_medica_db:/var/lib/mysql
  #    ports:
  #      - "3306:3306"
  #    restart: always

  frontend_pericia_medica:
    build: ./frontend
    ports:
      - "3023:80"
    restart: always
    network_mode: bridge

  backend_pericia_medica:
    #    depends_on:
    #      - mysql_container
    build: ./backend
    ports:
      - "3024:80"
    volumes:
      - ./backend/storage/:/var/www/html/storage/:delegated
      #- /filestorages:/filestorages
    restart: always
    network_mode: bridge

# volumes:
  #  pericia_medica_db:
